server:
  port: 1113

spring:
  application:
    name: SERVICE-ORDER2

#eureka.instance.prefer-ip-address 允许通过注册在eureka上的名字发现他的访问路径
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:1111/eureka/
  instance:
    prefer-ip-address: true
